---
default_desc: La guida completa ai pin GPIO del Raspberry Pi originale, del Modello
  B+ e del Raspberry Pi 2
default_title: Assegnazione pin GPIO del Raspberry Pi - Pi 1, B+, Pi 2
title_suffix: " - Assegnazione pin GPIO del Raspberry Pi"
base_url: /pinout/
resource_url: /resources/
domain: pinout.xyz
url_suffix:
urls:
  GND: ground
strings:
- made_by: '* Prodotto da {manufacturer}'
- type_hat: '* Fattore di forma HAT'
- type_classic: '* Fattore di forma classico'
- pin_header: '* {} pin header'
- uses_i2c: '* Utilizza I2C'
- wiring_pi_pin: 'Wiring Pi pin {}'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- display-o-tron-hat
- dots
- traffic-hat
- iqaudio-pi-dac
- piano-hat
- sense-hat
