---
default_desc: The comprehensive Raspberry Pi GPIO Pinout guide for the original Raspberry
  Pi, B+ and Pi 2
default_title: Raspberry Pi GPIO Pinout - Pi 1, B+, Pi 2
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: de.pinout.xyz
url_suffix:
urls:
  GND: masse_ground
strings:
- made_by: 'Hersteller: {manufacturer}'
- type_hat: 'HAT form-factor'
- type_classic: 'Classic form-factor'
- pin_header: '{} pin header'
- uses_i2c: 'benutzt I2C'
- uses_spi: 'benutzt SPI'
- wiring_pi_pin: 'Wiring Pi Anschluss {}'
- uses_n_gpio_pins: 'benutzt {} GPIO Anschl√ºsse'
- bcm_pin_rev1_pi: 'BCM Anschluss {} auf dem Rev 1 ( sehr alter ) Pi'
- physical_pin_n: 'Physical pin {}'
- more_information: 'Mehr Informationen'
- github_repository: 'GitHub Repository'
- buy_now: 'jetzt kaufen'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- display-o-tron-hat
- dots
- traffic-hat
- iqaudio-pi-dac
- piano-hat
- sense-hat
