---
default_desc: La guía detallada sobre el pinout del GPIO de Raspberry Pi para Raspberry
  Pi, B+ y Pi 2
default_title: Pinout de Raspberry Pi - Pi 1, B+, Pi 2
title_suffix: " at Raspberry Pi GPIO Pinout"
base_url: /pinout/
resource_url: /resources/
domain: es.pinout.xyz
url_suffix:
urls:
  GND: tierra
strings:
- made_by: 'Hecho por {manufacturer}'
- type_hat: 'formato HAT'
- type_classic: 'formato clásico'
- pin_header: '{} pin header'
- uses_i2c: 'Usa I2C'
- uses_spi: 'Usa SPI'
- wiring_pi_pin: 'Wiring Pi pin {}'
- uses_n_gpio_pins: ' Usa {} GPIO pins'
- bcm_pin_rev1_pi: 'BCM pin {} on Rev 1 ( very early ) Pi'
- physical_pin_n: 'Physical pin {}'
- more_information: 'More Information'
- github_repository: 'GitHub Repository'
- buy_now: 'Buy Now'
overlays:
- ground
- spi
- uart
- i2c
- wiringpi
- arduino-spi
- rtk-000-001
- piborg-ledborg
- piglow
- pibrella
- unicorn-hat
- skywriter-hat
- explorer-hat-pro
- explorer-hat
- display-o-tron
- display-o-tron-hat
- dots
- traffic-hat
- iqaudio-pi-dac
- piano-hat
- sense-hat
